---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, lib, bin, etc, var]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "PHP.cat"
keywords:    "PHP, català, programació, Catalunya, development, Catalonia, Països Catalans, Andorra, Rosselló, Perpinyà, València, País Valencià, Balears, Illes Balears, Mallorca, Barcelona, Barcelonès, Empordà"
description: "Pàgina web del grup PHP de llengua catalana"
source_link: "https://github.com/phpcat/phpcat"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-28522556-4


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
